name: lastsub
description: "LastSub - Track elapsed time since your last task."
publish_to: 'none'

version: 1.0.3+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: any
  riverpod_annotation: any
  freezed_annotation: any
  json_annotation: any
  uuid: any
  sqflite: any
  path: any
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  google_fonts: ^8.0.2
  fl_chart: ^1.2.0
  intl: ^0.20.2
  pdf: ^3.11.1
  printing: ^5.13.2
  flutter_local_notifications: ^18.0.0
  timezone: ^0.9.4
  logging: ^1.2.0
  google_mobile_ads: ^5.3.0

dev_dependencies:
  build_runner: any
  freezed: any
  json_serializable: any
  riverpod_generator: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/lastsub.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
