// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgyiW-jSLIEJnk2A5zvTSxRlLZMdoLXqA',
    appId: '1:544948745412:web:6df075f63ba2d3dc9c0591',
    messagingSenderId: '544948745412',
    projectId: 'itukara-3dd6b',
    authDomain: 'itukara-3dd6b.firebaseapp.com',
    storageBucket: 'itukara-3dd6b.firebasestorage.app',
    measurementId: 'G-XXWCQQCRQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg72RQy2IdmXAUT0SsmkJXc9jlSaaf7wk',
    appId: '1:544948745412:android:8d7753b51bbab1e19c0591',
    messagingSenderId: '544948745412',
    projectId: 'itukara-3dd6b',
    storageBucket: 'itukara-3dd6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxGi128TPDjlhw4d4zszxzKm3wzixorOk',
    appId: '1:544948745412:ios:e97da9c3123a52af9c0591',
    messagingSenderId: '544948745412',
    projectId: 'itukara-3dd6b',
    storageBucket: 'itukara-3dd6b.firebasestorage.app',
    iosBundleId: 'com.yuya.itukara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxGi128TPDjlhw4d4zszxzKm3wzixorOk',
    appId: '1:544948745412:ios:513f47b867a9753d9c0591',
    messagingSenderId: '544948745412',
    projectId: 'itukara-3dd6b',
    storageBucket: 'itukara-3dd6b.firebasestorage.app',
    iosBundleId: 'com.yuya.itukara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgyiW-jSLIEJnk2A5zvTSxRlLZMdoLXqA',
    appId: '1:544948745412:web:7f1f7345897ab7a79c0591',
    messagingSenderId: '544948745412',
    projectId: 'itukara-3dd6b',
    authDomain: 'itukara-3dd6b.firebaseapp.com',
    storageBucket: 'itukara-3dd6b.firebasestorage.app',
    measurementId: 'G-NY80WJG2S2',
  );
}
