import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import 'history_provider.dart';

// ── デザイントークン ─────────────────────────────────────
const _kAccent = PdfColor(0.00, 0.74, 0.83);       // #00BCD4 シアン
const _kDark = PdfColor(0.07, 0.07, 0.09);          // #121217 ほぼ黒
const _kSurface = PdfColor(0.96, 0.97, 0.98);       // #F5F7FA 極淡グレー
const _kBorder = PdfColor(0.88, 0.89, 0.91);        // #E1E4E8 罫線
const _kText = PdfColor(0.13, 0.15, 0.19);          // #212630 本文
const _kMuted = PdfColor(0.45, 0.49, 0.55);         // #737D8C サブテキスト

class PdfExportService {
  PdfExportService._();

  /// 履歴データを PDF に変換してシェアシートを呼び出す。
  static Future<void> export(
    BuildContext context,
    Map<String, List<GroupedTaskItem>> groupedByDate,
  ) async {
    final font = await PdfGoogleFonts.notoSansJPRegular();
    final fontBold = await PdfGoogleFonts.notoSansJPBold();

    final doc = pw.Document();
    final exportedAt = DateFormat('yyyy/MM/dd HH:mm').format(DateTime.now());

    final sortedDates = groupedByDate.keys.toList()
      ..sort((a, b) => b.compareTo(a));

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.symmetric(horizontal: 36, vertical: 40),
        theme: pw.ThemeData.withFont(base: font, bold: fontBold),
        header: (ctx) => _buildHeader(exportedAt, fontBold, font),
        footer: (ctx) => _buildFooter(ctx, font),
        build: (ctx) {
          final widgets = <pw.Widget>[];

          for (final dateStr in sortedDates) {
            final groups = groupedByDate[dateStr]!;
            widgets.add(_buildDateHeader(dateStr, fontBold));
            widgets.add(pw.SizedBox(height: 6));

            for (final group in groups) {
              widgets.add(_buildTaskSection(group, fontBold, font));
              widgets.add(pw.SizedBox(height: 10));
            }
            widgets.add(pw.SizedBox(height: 4));
          }

          return widgets;
        },
      ),
    );

    await Printing.sharePdf(
      bytes: await doc.save(),
      filename:
          'lastsub_${DateFormat('yyyyMMdd').format(DateTime.now())}.pdf',
    );
  }

  // ── ページヘッダー ────────────────────────────────────────
  static pw.Widget _buildHeader(
      String exportedAt, pw.Font fontBold, pw.Font font) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.stretch,
      children: [
        // ダークバー
        pw.Container(
          padding: const pw.EdgeInsets.symmetric(horizontal: 14, vertical: 10),
          decoration: const pw.BoxDecoration(color: _kDark),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Row(children: [
                // アクセントライン
                pw.Container(
                  width: 3,
                  height: 16,
                  margin: const pw.EdgeInsets.only(right: 8),
                  color: _kAccent,
                ),
                pw.Text(
                  'LastSub',
                  style: pw.TextStyle(
                    font: fontBold,
                    fontSize: 14,
                    color: PdfColors.white,
                    letterSpacing: 1.5,
                  ),
                ),
                pw.SizedBox(width: 8),
                pw.Text(
                  'タスク実行履歴',
                  style: pw.TextStyle(
                    font: font,
                    fontSize: 10,
                    color: const PdfColor(0.65, 0.68, 0.72),
                  ),
                ),
              ]),
              pw.Text(
                '出力: $exportedAt',
                style: pw.TextStyle(
                  font: font,
                  fontSize: 8,
                  color: const PdfColor(0.55, 0.58, 0.62),
                ),
              ),
            ],
          ),
        ),
        // アクセントライン
        pw.Container(height: 2, color: _kAccent),
        pw.SizedBox(height: 12),
      ],
    );
  }

  // ── ページフッター ───────────────────────────────────────
  static pw.Widget _buildFooter(pw.Context ctx, pw.Font font) {
    return pw.Column(children: [
      pw.Container(height: 0.5, color: _kBorder),
      pw.SizedBox(height: 6),
      pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Generated by LastSub',
            style: pw.TextStyle(font: font, fontSize: 7, color: _kMuted),
          ),
          pw.Text(
            '${ctx.pageNumber} / ${ctx.pagesCount}',
            style: pw.TextStyle(font: font, fontSize: 8, color: _kMuted),
          ),
        ],
      ),
    ]);
  }

  // ── 日付見出し ────────────────────────────────────────────
  static pw.Widget _buildDateHeader(String dateStr, pw.Font fontBold) {
    return pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.center,
      children: [
        pw.Container(width: 3, height: 18, color: _kAccent),
        pw.SizedBox(width: 8),
        pw.Text(
          dateStr,
          style: pw.TextStyle(
            font: fontBold,
            fontSize: 13,
            color: _kText,
            letterSpacing: 0.5,
          ),
        ),
        pw.SizedBox(width: 10),
        pw.Expanded(
          child: pw.Container(height: 0.5, color: _kBorder),
        ),
      ],
    );
  }

  // ── タスクセクション（タスク名 + テーブル）───────────────
  static pw.Widget _buildTaskSection(
      GroupedTaskItem group, pw.Font fontBold, pw.Font font) {
    final task = group.task;

    return pw.Container(
      margin: const pw.EdgeInsets.only(left: 11),
      decoration: pw.BoxDecoration(
        border: const pw.Border(
          left: pw.BorderSide(color: _kBorder, width: 1),
        ),
      ),
      child: pw.Padding(
        padding: const pw.EdgeInsets.only(left: 10),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            // タスク名行
            pw.Row(children: [
              pw.Text(
                task.title,
                style: pw.TextStyle(
                  font: fontBold,
                  fontSize: 10,
                  color: _kText,
                ),
              ),
              pw.SizedBox(width: 8),
              pw.Container(
                padding:
                    const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                decoration: pw.BoxDecoration(
                  color: _kAccent,
                  borderRadius: const pw.BorderRadius.all(pw.Radius.circular(3)),
                ),
                child: pw.Text(
                  '${group.count}回',
                  style: pw.TextStyle(
                    font: fontBold,
                    fontSize: 8,
                    color: PdfColors.white,
                  ),
                ),
              ),
            ]),
            pw.SizedBox(height: 5),
            // データテーブル
            _buildTable(group, fontBold, font),
          ],
        ),
      ),
    );
  }

  // ── データテーブル ────────────────────────────────────────
  static pw.Widget _buildTable(
      GroupedTaskItem group, pw.Font fontBold, pw.Font font) {
    final headerStyle = pw.TextStyle(
        font: fontBold, fontSize: 8, color: PdfColors.white);
    final dataStyle =
        pw.TextStyle(font: font, fontSize: 8, color: _kText);
    final mutedStyle =
        pw.TextStyle(font: font, fontSize: 8, color: _kMuted);

    final headerRow = pw.TableRow(
      decoration: const pw.BoxDecoration(color: _kDark),
      children: [
        _cell('#', style: headerStyle, align: pw.Alignment.center),
        _cell('記録時刻', style: headerStyle),
        _cell('開始時刻', style: headerStyle),
        _cell('作業時間', style: headerStyle),
        _cell('値', style: headerStyle, align: pw.Alignment.centerRight),
      ],
    );

    final dataRows = group.items.asMap().entries.map((e) {
      final idx = e.key;
      final r = e.value.record;
      final isEven = idx.isEven;

      final recordedStr = DateFormat('HH:mm').format(r.recordedAt);
      final startedStr =
          r.startedAt != null ? DateFormat('HH:mm').format(r.startedAt!) : '—';
      final durationStr = r.startedAt != null
          ? _formatDuration(r.recordedAt.difference(r.startedAt!))
          : '—';
      final valueStr = r.value != null
          ? '${r.value!.toStringAsFixed(r.value! % 1 == 0 ? 0 : 1)}${r.unit ?? ''}'
          : '—';

      return pw.TableRow(
        decoration: pw.BoxDecoration(
          color: isEven ? _kSurface : PdfColors.white,
        ),
        children: [
          _cell('${idx + 1}', style: mutedStyle, align: pw.Alignment.center),
          _cell(recordedStr, style: dataStyle),
          _cell(startedStr, style: mutedStyle),
          _cell(durationStr, style: dataStyle),
          _cell(valueStr, style: dataStyle, align: pw.Alignment.centerRight),
        ],
      );
    }).toList();

    return pw.Table(
      border: pw.TableBorder(
        bottom: const pw.BorderSide(color: _kBorder, width: 0.5),
      ),
      columnWidths: {
        0: const pw.FixedColumnWidth(24),
        1: const pw.FixedColumnWidth(48),
        2: const pw.FixedColumnWidth(48),
        3: const pw.FlexColumnWidth(),
        4: const pw.FixedColumnWidth(52),
      },
      children: [headerRow, ...dataRows],
    );
  }

  static pw.Widget _cell(
    String text, {
    required pw.TextStyle style,
    pw.Alignment align = pw.Alignment.centerLeft,
  }) =>
      pw.Container(
        alignment: align,
        padding: const pw.EdgeInsets.symmetric(horizontal: 5, vertical: 4),
        child: pw.Text(text, style: style),
      );

  static String _formatDuration(Duration d) {
    final h = d.inHours;
    final m = d.inMinutes % 60;
    final s = d.inSeconds % 60;
    if (h > 0) return '$h時間$m分';
    if (m > 0) return '$m分$s秒';
    return '$s秒';
  }
}
